[tool.poetry]
name = "bnb-rag-api"
version = "0.1.0"
description = "API for BNB RAG Bot"
authors = ["petriccone <your-email@example.com>"]

[tool.poetry.scripts]
app = "platform_backend.main:app"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
